FROM alpine:edge
RUN apk --no-cache add dnsmasq
RUN mkdir /tftp
RUN wget "https://rom-o-matic.eu/build.fcgi?BINARY=ipxe.kpxe&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=&settings.h/CPUID_SETTINGS:=1&settings.h/ACPI_SETTINGS:=1&general.h/NET_PROTO_IPV6:=1&general.h/NET_PROTO_FCOE:=1&general.h/DOWNLOAD_PROTO_HTTPS:=1&general.h/DOWNLOAD_PROTO_FTP:=1&general.h/DOWNLOAD_PROTO_SLAM:=1&general.h/DOWNLOAD_PROTO_NFS:=1&general.h/DOWNLOAD_PROTO_FILE:=1&general.h/SANBOOT_PROTO_ISCSI:=1&general.h/SANBOOT_PROTO_AOE:=1&general.h/SANBOOT_PROTO_IB_SRP:=1&general.h/SANBOOT_PROTO_FCP:=1&general.h/SANBOOT_PROTO_HTTP:=1&general.h/HTTP_ENC_PEERDIST:=1&general.h/HTTP_HACK_GCE:=1&general.h/IMAGE_SCRIPT:=1&general.h/IMAGE_PNM:=1&general.h/NSLOOKUP_CMD:=1&general.h/TIME_CMD:=1&general.h/DIGEST_CMD:=1&general.h/LOTEST_CMD:=1&general.h/VLAN_CMD:=1&general.h/REBOOT_CMD:=1&general.h/POWEROFF_CMD:=1&general.h/IMAGE_TRUST_CMD:=1&general.h/PCI_CMD:=1&general.h/PARAM_CMD:=1&general.h/NEIGHBOUR_CMD:=1&general.h/PING_CMD:=1&general.h/CONSOLE_CMD:=1&general.h/IPSTAT_CMD:=1&general.h/PROFSTAT_CMD:=1&general.h/NTP_CMD:=1&general.h/CERT_CMD:=1&general.h/VNIC_XSIGO:=1&general.h/BUILD_SERIAL:=1&general.h/BUILD_ID:=1&branding.h/PRODUCT_SHORT_NAME=COACH&branding.h/PRODUCT_TAG_LINE=Cluster%20of%20Arbitrary%20Cheap%20Hardware&" -O /tftp/ipxe.kpxe
RUN wget "https://rom-o-matic.eu/build.fcgi?BINARY=ipxe.efi&BINDIR=bin-i386-efi&REVISION=master&DEBUG=&EMBED.00script.ipxe=&settings.h/CPUID_SETTINGS:=1&settings.h/ACPI_SETTINGS:=1&general.h/NET_PROTO_IPV6:=1&general.h/NET_PROTO_FCOE:=1&general.h/DOWNLOAD_PROTO_HTTPS:=1&general.h/DOWNLOAD_PROTO_FTP:=1&general.h/DOWNLOAD_PROTO_SLAM:=1&general.h/DOWNLOAD_PROTO_NFS:=1&general.h/DOWNLOAD_PROTO_FILE:=1&general.h/SANBOOT_PROTO_ISCSI:=1&general.h/SANBOOT_PROTO_AOE:=1&general.h/SANBOOT_PROTO_IB_SRP:=1&general.h/SANBOOT_PROTO_FCP:=1&general.h/SANBOOT_PROTO_HTTP:=1&general.h/HTTP_ENC_PEERDIST:=1&general.h/HTTP_HACK_GCE:=1&general.h/IMAGE_SCRIPT:=1&general.h/IMAGE_PNM:=1&general.h/NSLOOKUP_CMD:=1&general.h/TIME_CMD:=1&general.h/DIGEST_CMD:=1&general.h/LOTEST_CMD:=1&general.h/VLAN_CMD:=1&general.h/REBOOT_CMD:=1&general.h/POWEROFF_CMD:=1&general.h/IMAGE_TRUST_CMD:=1&general.h/PCI_CMD:=1&general.h/PARAM_CMD:=1&general.h/NEIGHBOUR_CMD:=1&general.h/PING_CMD:=1&general.h/CONSOLE_CMD:=1&general.h/IPSTAT_CMD:=1&general.h/PROFSTAT_CMD:=1&general.h/NTP_CMD:=1&general.h/CERT_CMD:=1&general.h/VNIC_XSIGO:=1&general.h/BUILD_SERIAL:=1&general.h/BUILD_ID:=1&branding.h/PRODUCT_SHORT_NAME=COACH&branding.h/PRODUCT_TAG_LINE=Cluster%20of%20Arbitrary%20Cheap%20Hardware&" -O /tftp/ipxe_32.efi
RUN wget "https://rom-o-matic.eu/build.fcgi?BINARY=ipxe.efi&BINDIR=bin-x86_64-efi&REVISION=master&DEBUG=&EMBED.00script.ipxe=&settings.h/CPUID_SETTINGS:=1&settings.h/ACPI_SETTINGS:=1&general.h/NET_PROTO_IPV6:=1&general.h/NET_PROTO_FCOE:=1&general.h/DOWNLOAD_PROTO_HTTPS:=1&general.h/DOWNLOAD_PROTO_FTP:=1&general.h/DOWNLOAD_PROTO_SLAM:=1&general.h/DOWNLOAD_PROTO_NFS:=1&general.h/DOWNLOAD_PROTO_FILE:=1&general.h/SANBOOT_PROTO_ISCSI:=1&general.h/SANBOOT_PROTO_AOE:=1&general.h/SANBOOT_PROTO_IB_SRP:=1&general.h/SANBOOT_PROTO_FCP:=1&general.h/SANBOOT_PROTO_HTTP:=1&general.h/HTTP_ENC_PEERDIST:=1&general.h/HTTP_HACK_GCE:=1&general.h/IMAGE_SCRIPT:=1&general.h/IMAGE_PNM:=1&general.h/NSLOOKUP_CMD:=1&general.h/TIME_CMD:=1&general.h/DIGEST_CMD:=1&general.h/LOTEST_CMD:=1&general.h/VLAN_CMD:=1&general.h/REBOOT_CMD:=1&general.h/POWEROFF_CMD:=1&general.h/IMAGE_TRUST_CMD:=1&general.h/PCI_CMD:=1&general.h/PARAM_CMD:=1&general.h/NEIGHBOUR_CMD:=1&general.h/PING_CMD:=1&general.h/CONSOLE_CMD:=1&general.h/IPSTAT_CMD:=1&general.h/PROFSTAT_CMD:=1&general.h/NTP_CMD:=1&general.h/CERT_CMD:=1&general.h/VNIC_XSIGO:=1&general.h/BUILD_SERIAL:=1&general.h/BUILD_ID:=1&branding.h/PRODUCT_SHORT_NAME=COACH&branding.h/PRODUCT_TAG_LINE=Cluster%20of%20Arbitrary%20Cheap%20Hardware&" -O /tftp/ipxe_64.efi
COPY /pxe.conf /etc/dnsmasq.d/pxe.conf
EXPOSE 67 69
ENTRYPOINT ["dnsmasq", "-d", "--conf-dir=/etc/dnsmasq.d" ]
